### ISSUE TITLE
我把数据库驱动改成了ORACLE，启动的时候提示org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'enableRedisKeyspaceNotificationsInitializer' defined in class path resource [org/springframework/session/data/redis/config/annotation/web/http/RedisHttpSessionConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool 

### ISSUE THREAD

**Issue by baozg1126** [zhuzhengping911/MySpringBoot#1]
你好

我把数据库驱动改成了ORACLE，

改的位置
/resources/config/DBsource.properties
/resources/application.yml    hibernate的驱动也换了

直接运行提示表名不能用，我在user那添加了注释@Table(name="t_user")

然后运行
启动的时候提示org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'enableRedisKeyspaceNotificationsInitializer' defined in class path resource 
[org/springframework/session/data/redis/config/annotation/web/http/RedisHttpSessionConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection;
 nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool 
 
 网上说是redis 这个的配置问题 ，求解

**Comment by zhuzhengping911** [comment]
如果你不使用redis的话，就把pom中的redis依赖注释掉，如果使用，确保你机器上已经安装了redis

**Comment by baozg1126** [comment]
已经借鉴其他办法解决，还是谢谢你 。

**Comment by baozg1126** [comment]
OK ，我再找下相关的资料看下 。



夜的轨迹
251528115@qq.com
 
发件人： zhengping.zhu
发送时间： 2017-10-09 17:14
收件人： zhuzhengping911/MySpringBoot
抄送： baozg1126; Author
主题： Re: [zhuzhengping911/MySpringBoot] 我把数据库驱动改成了ORACLE，启动的时候提示org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'enableRedisKeyspaceNotificationsInitializer' defined in class path resource [org/springframework/session/data/redis/config/annotation/web/http/RedisHttpSessionConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool (#1)
如果你不使用redis的话，就把pom中的redis依赖注释掉，如果使用，确保你机器上已经安装了redis
