### ISSUE TITLE
关于统一异常处理的问题

### ISSUE THREAD

**Issue by lalalazero** [zhuzhengping911/MySpringBoot#2]
你好，我读了关于统一异常处理的博客文章，我想问个问题。
我现在也是写了一个类似的异常处理，代码如下：
`
@ControllerAdvice
public class GlobalExceptionHandler {

    private final Logger logger = LoggerFactory.getLogger(GlobalExceptionHandler.class);

    @ExceptionHandler(MultipartException.class)
    @ResponseStatus(HttpStatus.OK)
    @ResponseBody
    public Object exceedFileSizeHandler(MultipartException ex)
    {
        logger.error("文件上传异常={}",ex.getMessage());
        return ResponseDTO.fail("文件上传大小超过10M");
    }

}
`
我希望这个post请求能正常返回，然后在前台的ajax的success回调函数里，我可以拿到这个fail的提示，但是现在我的请求一直都是失败的返回，直接进了ajax的error回调函数，请问像这种异常处理你的前台请求是怎么写的呢？

**Comment by zhuzhengping911** [comment]
1.使用特定code与前端约定，该code不用进error处理逻辑
2.将该错误修改为成功，msg内给出提示信息，作为正常返回
